#!/usr/bin/env bash
export PLUGIN_COMMAND_PREFIX="cloudflare"
export CLOUDFLARE_TOKEN=${CLOUDFLARE_TOKEN:="!notset"}
export CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL:="!notset"}
export CLOUDFLARE_ZONE=${CLOUDFLARE_ZONE:="!notset"}
