#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
PLUGIN_BASE_PATH="$PLUGIN_PATH"
if [[ -n $DOKKU_API_VERSION ]]; then
  PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi
source "$PLUGIN_BASE_PATH/common/functions"

RELEASE_BASE="https://github.com/bkono/dokku-cloudflare-src/releases/download/0.0.1/dokku-cloudflare"
ARCH=$(uname -m)
BINARY_PATH="$(dirname "$0")/dokku-cloudflare"
if [ "$ARCH" == "x86_64" ]; then
  ARCH="amd64"
else 
  ARCH="386"
fi

case $(uname -s) in
  Linux) 
    RELEASE="${RELEASE_BASE}_linux_$ARCH"
    dokku_log_info2 "Linux detected. arch=$ARCH"
    ;;
  Darwin)
    RELEASE="${RELEASE_BASE}_darwin_$ARCH"
    dokku_log_info2 "Darwin detected. arch=$ARCH"
    ;;
  *) dokku_log_fail "Unsupported architecture and OS combination: $(uname -s) $ARCH";;
esac

curl -L -s $RELEASE > $BINARY_PATH
chown dokku:dokku $BINARY_PATH
chmod +x $BINARY_PATH

